const COOKIE="quran_revision_session", enc=new TextEncoder(), ITERATIONS=100000;
function b64u(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function ub64(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
function rand(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
async function hashPassword(password,salt=rand(16)){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:ITERATIONS,hash:"SHA-256"},key,256);return `${b64u(salt)}.${b64u(new Uint8Array(bits))}`}
async function verifyPassword(password,stored){const [s,h]=stored.split(".");const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:ub64(s),iterations:ITERATIONS,hash:"SHA-256"},key,256));const want=ub64(h);let diff=bits.length^want.length;for(let i=0;i<bits.length&&i<want.length;i++)diff|=bits[i]^want[i];return diff===0}
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store",...headers}})}
function cookie(v,maxAge){return `${COOKIE}=${v}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function tokenFrom(req){const c=req.headers.get("Cookie")||"";for(const p of c.split(";")){const [k,...v]=p.trim().split("=");if(k===COOKIE)return v.join("=")}return null}
function id(){return b64u(rand(18))}
async function getUser(req,env){const t=tokenFrom(req);if(!t)return null;return await env.DB.prepare("SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.created_at>?").bind(t,Date.now()-30*86400000).first()}
async function body(req){return await req.json().catch(()=>({}))}
function validSurah(n){return Number.isInteger(n)&&n>=1&&n<=114}
async function main(req,env){const url=new URL(req.url),p=url.pathname,m=req.method;
 if(p==="/api/health")return json({ok:true});
 if(p==="/api/me"&&m==="GET"){const u=await getUser(req,env);return json(u?{loggedIn:true,username:u.username}:{loggedIn:false})}
 if(p==="/api/signup"&&m==="POST"){const b=await body(req),username=String(b.username||"").trim(),password=String(b.password||"");if(!/^[A-Za-z0-9_]{3,24}$/.test(username))return json({error:"Username must be 3–24 characters using letters, numbers, or _."},400);if(password.length<8||password.length>128)return json({error:"Password must be 8–128 characters."},400);if(await env.DB.prepare("SELECT id FROM users WHERE username=? COLLATE NOCASE").bind(username).first())return json({error:"That username is already taken."},409);const uid=id(),now=Date.now();await env.DB.prepare("INSERT INTO users(id,username,password_hash,created_at) VALUES(?,?,?,?)").bind(uid,username,await hashPassword(password),now).run();const t=id()+id();await env.DB.prepare("INSERT INTO sessions(token,user_id,created_at) VALUES(?,?,?)").bind(t,uid,now).run();return json({ok:true},200,{"set-cookie":cookie(t,2592000)})}
 if(p==="/api/login"&&m==="POST"){const b=await body(req),username=String(b.username||"").trim(),password=String(b.password||"");const u=await env.DB.prepare("SELECT id,username,password_hash FROM users WHERE username=? COLLATE NOCASE").bind(username).first();if(!u||!(await verifyPassword(password,u.password_hash)))return json({error:"Incorrect username or password."},401);const t=id()+id();await env.DB.prepare("INSERT INTO sessions(token,user_id,created_at) VALUES(?,?,?)").bind(t,u.id,Date.now()).run();return json({ok:true},200,{"set-cookie":cookie(t,2592000)})}
 if(p==="/api/logout"&&m==="POST"){const t=tokenFrom(req);if(t)await env.DB.prepare("DELETE FROM sessions WHERE token=?").bind(t).run();return json({ok:true},200,{"set-cookie":cookie("",0)})}
 const u=await getUser(req,env);if(p.startsWith("/api/")&&!u)return json({error:"Please sign in."},401);
 if(p==="/api/data"&&m==="GET"){const [surahs,ayahs,logs,homework]=await Promise.all([env.DB.prepare("SELECT surah,memorized,rating,last_read,notes,updated_at FROM surah_progress WHERE user_id=? ORDER BY surah").bind(u.id).all(),env.DB.prepare("SELECT surah,ayah,rating,weak,updated_at FROM ayah_progress WHERE user_id=? ORDER BY surah,ayah").bind(u.id).all(),env.DB.prepare("SELECT id,surah,ayah_start,ayah_end,read_at,kind FROM reading_log WHERE user_id=? ORDER BY read_at DESC LIMIT 2000").bind(u.id).all(),env.DB.prepare("SELECT id,assigned_at,minutes_target,payload,completed_at,actual_minutes FROM homework_log WHERE user_id=? ORDER BY assigned_at DESC LIMIT 30").bind(u.id).all()]);return json({username:u.username,surahs:surahs.results,ayahs:ayahs.results,logs:logs.results,homework:homework.results.map(x=>({...x,payload:JSON.parse(x.payload)}))})}
 if(p==="/api/onboarding"&&m==="POST"){const b=await body(req),items=Array.isArray(b.surahs)?b.surahs:[],now=Date.now();const stmts=[];for(const x of items){const s=Number(x.surah),r=Number(x.rating);if(validSurah(s)&&Number.isInteger(r)&&r>=1&&r<=6)stmts.push(env.DB.prepare("INSERT INTO surah_progress(user_id,surah,memorized,rating,updated_at) VALUES(?,?,1,?,?) ON CONFLICT(user_id,surah) DO UPDATE SET memorized=1,rating=excluded.rating,updated_at=excluded.updated_at").bind(u.id,s,r,now))}if(stmts.length)await env.DB.batch(stmts);return json({ok:true})}
 const sm=p.match(/^\/api\/surahs\/(\d+)$/);if(sm&&m==="PUT"){const s=Number(sm[1]),b=await body(req);if(!validSurah(s))return json({error:"Invalid Surah."},400);const r=Math.max(1,Math.min(6,Number(b.rating)||3)),last=b.last_read==null?null:Number(b.last_read),notes=String(b.notes??"").slice(0,10000),mem=b.memorized===false?0:1;await env.DB.prepare("INSERT INTO surah_progress(user_id,surah,memorized,rating,last_read,notes,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,surah) DO UPDATE SET memorized=excluded.memorized,rating=excluded.rating,last_read=excluded.last_read,notes=excluded.notes,updated_at=excluded.updated_at").bind(u.id,s,mem,r,last,notes,Date.now()).run();return json({ok:true})}
 const am=p.match(/^\/api\/surahs\/(\d+)\/ayahs\/(\d+)$/);if(am&&m==="PUT"){const s=Number(am[1]),a=Number(am[2]),b=await body(req),r=b.rating==null?null:Number(b.rating),weak=b.weak?1:0;if(!validSurah(s)||!Number.isInteger(a)||a<1||a>286||(r!==null&&(!Number.isInteger(r)||r<1||r>6)))return json({error:"Invalid ayah update."},400);await env.DB.prepare("INSERT INTO ayah_progress(user_id,surah,ayah,rating,weak,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,surah,ayah) DO UPDATE SET rating=excluded.rating,weak=excluded.weak,updated_at=excluded.updated_at").bind(u.id,s,a,r,weak,Date.now()).run();return json({ok:true})}
 if(p==="/api/read"&&m==="POST"){const b=await body(req),s=Number(b.surah),a1=Number(b.ayah_start)||1,a2=Number(b.ayah_end)||a1,at=Number(b.read_at)||Date.now();if(!validSurah(s)||a1<1||a2<a1||a2>286)return json({error:"Invalid reading log."},400);await env.DB.prepare("INSERT INTO reading_log(id,user_id,surah,ayah_start,ayah_end,read_at,kind) VALUES(?,?,?,?,?,?,?)").bind(id(),u.id,s,a1,a2,at,String(b.kind||"read")).run();await env.DB.prepare("UPDATE surah_progress SET last_read=?,updated_at=? WHERE user_id=? AND surah=?").bind(at,Date.now(),u.id,s).run();return json({ok:true})}
 if(p==="/api/homework"&&m==="POST"){const b=await body(req),minutes=Math.max(5,Math.min(180,Number(b.minutes)||20)),payload=b.payload||{};const hid=id();await env.DB.prepare("INSERT INTO homework_log(id,user_id,assigned_at,minutes_target,payload) VALUES(?,?,?,?,?)").bind(hid,u.id,Date.now(),minutes,JSON.stringify(payload)).run();return json({ok:true,id:hid})}
 const hm=p.match(/^\/api\/homework\/([^/]+)\/complete$/);if(hm&&m==="POST"){const b=await body(req);await env.DB.prepare("UPDATE homework_log SET completed_at=?,actual_minutes=? WHERE id=? AND user_id=?").bind(Date.now(),Math.max(1,Number(b.actual_minutes)||1),hm[1],u.id).run();return json({ok:true})}
 return env.ASSETS.fetch(req)
}
export default {async fetch(req,env){try{return await main(req,env)}catch(e){console.error(e);return json({error:"Server error."},500)}}};
